const inputs = {
  checkboxicon: {
    checked: false,
    name: 'checkbox-icon',
    value: 'check',
    icon: 'check',
    text: 'Checkbox Label',
    required: false,
    message: {
      error: {
        invalid: 'You done fucked up, son!',
      },
    },
  },
  checkbox: {
    checked: false,
    name: '',
    value: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  date: {
    name: '',
    value: '',
    min: '',
    max: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  email: {
    name: '',
    placeholder: 'name.surname@company.tld',
    value: '',
    maxlength: 256,
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  image: {
    name: '',
    value: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  number: {
    name: '',
    placeholder: '',
    value: '',
    min: '',
    max: '',
    step: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  password: {
    name: '',
    placeholder: '',
    value: '',
    maxlength: 256,
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  pdf: {
    name: '',
    value: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  radio: {
    checked: false,
    name: '',
    value: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  range: {
    name: '',
    value: '',
    min: 1,
    max: 10,
    step: 1,
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  select: {
    name: '',
    value: '',
    text: 'Choose an option',
    options: [
      {
        value: 'option-1',
        text: 'Option 1',
      },
      {
        value: 'option-2',
        text: 'Option 2',
      },
      {
        value: 'option-3',
        text: 'Option 3',
      },
    ],
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  text: {
    name: '',
    placeholder: '',
    value: '',
    maxlength: 256,
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  textarea: {
    name: '',
    placeholder: '',
    value: '',
    maxlength: 256,
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  toggle: {
    checked: false,
    name: '',
    value: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
  url: {
    name: '',
    placeholder: 'https://www.website.com',
    value: '',
    text: '',
    required: false,
    message: { error: { invalid: 'Generic error message' } },
  },
};

module.exports = inputs;
